### ISSUE TITLE
The summary screen and the use of Wald's test for parameters

### ISSUE THREAD

**Issue by haziqj** [haziqjamil/iprior#5]
Perhaps a better test of hypothesis for the parameters is a log-likelihood ratio test. This is much simpler to implement. Also, what test do we want for psi?

On an aesthetic note, change the `alpha` parameter name to `(Intercept)`, as some users might not be familiar with what `alpha` is.

**Comment by haziqj** [comment]
After discussion, the Wald's test is a convenient and fast way to test the significance of the `lambda` parameters. However, this is not valid for the `psi` or error variance parameter. Instead, just report the estimate for the error variance in the summary screen, along with its standard error (use delta method to convert from `psi`).

In general, report the error variance instead of `psi`.

**Comment by haziqjamil** [comment]
Standard deviation of errors is reported now in the summary screen (instead of `psi`). This is consistent with `lm`'s reporting of the "residual standard errors". However, in the `iprior` print, this still displays `psi` which I think is worthwhile keeping. 

In any case, both of these parameters are stored in the I-prior model, namely `mod.iprior$sigma` and `mod.iprior$psi`.

**Comment by haziqj** [comment]
Standard deviation of errors is reported now in the summary screen (instead of `psi`). This is consistent with `lm`'s reporting of the "residual standard errors". However, in the `iprior` print, this still displays `psi` which I think is worthwhile keeping. 

In any case, both of these parameters are stored in the I-prior model, namely `mod.iprior$sigma` and `mod.iprior$psi`.
